title: Rohan Khetan
description: Writing on things I find interesting.
url: "https://rokhet10.github.io"
baseurl: "/blog"

author:
  name: Rohan Khetan

paginate: 9
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge
permalink: /:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - vendor
